### ISSUE TITLE
FXAA Problem on Windows

### ISSUE THREAD

**Issue by PseudoFreak** [BennyQBD/3DEngineCpp#10]
The current version of the engine gives the error message "Error linking shader program: Fragment shader writes to more than 1 type of output gl_FragData, gl_FragColor or user bound frag data.". The error occurs while compiling filter-fxaa.fs.

**Comment by pythoneer** [comment]
A detailed description about that problem would be great :)

//EDIT:

Sry, your post was empty as i encountered your issue post..

**Comment by PseudoFreak** [comment]
Well, there is nothing more to say, the `CompileShader()` tries to link the program with `glLinkProgram()`, fails and calls `CheckShaderError()`. And `CheckShaderError()` gives the error message `"Error linking shader program: Fragment shader writes to more than 1 type of output gl_FragData, gl_FragColor or user bound frag data."`
The error message with a GeForce GTX 760 is quite similar: `"error:  user-defined fragment shader outputs may not be used with gl_FragColor or gl_FragData'Invalid shader program"`

**Comment by ForeverTPS** [comment]
I have the same issue with some added details:

```
Error linking shader program: 'Fragment info
-------------
0(47) warning C7533: global variable gl_FragColor is depreciated after version 120
error: user-defined fragment shader outputs may not be used with gl_FragColor or gl_FragData'
Invalid shader program: ''
Assertion failed: location != INVALID_VALUE
```

It seems to be related to GLSL version. If you comment out the conversion to version 330 in the ShaderData constructor it works (see the 3 lines commented out):

```
if (s_supportedGLSLLevel >= 330)
{
    //ConvertVertexShaderToGLSL330(&vertexShaderText);
    //ConvertFragmentShaderToGLSL330(&fragmentShaderText);
}

AddVertexShader(vertexShaderText);
AddFragmentShader(fragmentShaderText);

//if (s_supportedGLSLLevel < 330)
{
    AddAllAttributes(vertexShaderText);
}
```

**Comment by BennyQBD** [comment]
There was a slight bug in the GLSL 3.3 update code. It should be resolved now.

**Comment by ForeverTPS** [comment]
I was just about to post the fix but you beat me to it Benny :-)
