### ISSUE TITLE
Bad context creation on apple macs (at least for me)

### ISSUE THREAD

**Issue by citruslee** [BennyQBD/3DEngineCpp#12]
Hello, I found out, that in Mavericks you should extend the window.cpp with these lines to around 26th line:

```
SDL_GL_SetAttribute( SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE );
SDL_GL_SetAttribute( SDL_GL_CONTEXT_MAJOR_VERSION, 3 );
SDL_GL_SetAttribute( SDL_GL_CONTEXT_MINOR_VERSION, 2 );
```

this should fix the problems maybe, for me, it was resolved after this, hence the stock SDL context created was for glsl 1.20...here is the error log if I remove those lines

```
Supported GLSL version is 1.20.
Error compiling shader type 2: 'ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:2: 'layout' : syntax error syntax error

Program ended with exit code: 1
```

**Comment by BennyQBD** [comment]
You're absolutely right, and this is something I've been meaning to do for a while, but I hadn't gotten around to it. I've updated the repository, let me know if you have any issues.

**Comment by citruslee** [comment]
for now, it is all, everything works for now, if there will be issues, I will post you :) And I have also a proposal, I've made scripting in LUA to your Java version of engine, but it is in very early stage of development, now I want to implement it to C++. Maybe there will be Mono (C# scripting) if you want, I will provide you code if it will be done
