### ISSUE TITLE
Light & Paralax Mapping glitches

### ISSUE THREAD

**Issue by pythoneer** [BennyQBD/3DEngineCpp#14]
Hi, today i encountered some glitches with the rendering of the Light in combination with the Paralax Mapping. Right now i am trying to find a commit where this is not occurring, i wonder if this is a new glitch or i simply did no recognized this. Maybe it hast something to do with a new graphics driver .. i really wonder why i did not recognized this in earlier commits ...

https://www.youtube.com/watch?v=jJeSTRz-mU8

archlinux 3.14.5-1
nvidia 337.25 xorg 1.15
GTX 750 Ti

**Comment by PseudoFreak** [comment]
You mean the flickering? You didn't change the TestGame scene? I can reproduce this neither on Windows 7 (an Intel integrated card) nor on Windows 8 (GeForce GTX 760).

**Comment by pythoneer** [comment]
No its from a fresh git pull ... and some git checkouts of older versions. i guess it has something to do with my driver cuz i did not see this earlier. but when i go back a few commits its still there ... :/

**Comment by BennyQBD** [comment]
I can't reproduce the issue with my current version of the code. I'll go ahead and push my changes so you can see if that fixes anything for you. However, I suspect it's a driver issue.

**Comment by ForeverTPS** [comment]
I also have this issue but will check with your latest commit. I'm on Windows 7 with a GTX 770 (337.88 driver)

Just one thing that confuses me in the latest commit in shader.cpp (line 59):

```
if(s_supportedOpenGLLevel >= 320)
{
    ConvertVertexShaderToGLSL150(&vertexShaderText);
    ConvertFragmentShaderToGLSL150(&fragmentShaderText);
}
```

Should that not be less than or equal to or am I misunderstanding?

**Comment by BennyQBD** [comment]
OpenGL 3.2 uses GLSL 150, so yes that's actually correct. Don't ask me; I don't know why they created GLSL versions like that either.

**Comment by ForeverTPS** [comment]
Yeah sorry I just realised how it works now.

**Comment by ForeverTPS** [comment]
Latest code tested, issue still occurring. Only appears when viewing in this direction:

![capture](https://cloud.githubusercontent.com/assets/1371608/3300786/9997d74c-f624-11e3-8f9a-dcc07ff08611.PNG)

**Comment by BennyQBD** [comment]
Are you talking about flickering or the fact that there's lines in the specular highlight? If the latter, that's because normal mapping/parallax mapping is an approximation, and the light is at a bad angle for that.

If you're talking about flickering, I still can't reproduce the issue.

**Comment by ForeverTPS** [comment]
I was referring to the highlight along the left side of the blocks in the image above. I don't think I have seen any flickering though (other than the flickering in the highlight)

**Comment by BennyQBD** [comment]
If it's flickering in the highlight, then that's the issue, and sorry but I still can't reproduce the issue. I still believe this is a graphics driver issue.

**Comment by pythoneer** [comment]
Sry for not participating the last few days. 
@BennyQBD yes its about these artifacts in the highlights one can clearly see in Zammalads picture and in my video. I think we cant do much about that, lets see how this develops with newer versions of the nvidia Driver. @PseudoFreak could you post your Driverversion?

**Comment by ForeverTPS** [comment]
I have upgraded from the 337.88 driver to 340.43 Beta driver and the issue remains.

**Comment by PseudoFreak** [comment]
@pythoneer I've noticed that i've been using different normal maps, I actually can reproduce the problem (on the Windows 8, GeForce GTX 760 machine) with Benny's normal map. I don't think this is a big problem, though.

**Comment by BennyQBD** [comment]
I just fixed a bug in the lighting, see if it fixed this as well.

**Comment by ForeverTPS** [comment]
I have tested the latest changes in the lighting and confirm it appears to have resolved the issue for me:

![capture](https://cloud.githubusercontent.com/assets/1371608/3379381/fafde1bc-fbf0-11e3-8315-86b9561b8bf5.PNG)

**Comment by pythoneer** [comment]
@BennyQBD Oh dear lord :D not only the lightning artifacts are gone, the overall rendering quality increased a LOT! Especially the shadows in the normal mapped "landscape" ... the tiny holes casting shadow from the directional light. ( i bet that's coming from the issue with the bust ) Thanks Benny. I think we can close the issue at this point – solved.
