### ISSUE TITLE
It's me...again...

### ISSUE THREAD

**Issue by citruslee** [BennyQBD/3DEngineCpp#16]
Hello, I've recently tried to build the modified code you made when I proposed you to put preprocessor macro to the version setting in window.cpp...it works flawless with Windows 8.1 and MSVC 12 (2013) but it throws me error for OpenGL context as far as I don't remove or comment out those lines of setting up GL version via SDL...I'm truly sorry to bug you around with this crap, but on the other side, it should be cured in some way

**Comment by BennyQBD** [comment]
I'm sorry, but what causes the error (i.e. what platform, os, gpu, openGL version, etc. and what steps)? Also what exactly is the error it gives you?

**Comment by citruslee** [comment]
sorry, the error I can't provide you at this moment, hence the computer I've tried is at my friend, but it was on Windows 8.0 with MSVC 11 (2012) compiler, gpu is an nvidia GT555m card (Dell xps l702x) with the latest nvidia drivers (non beta). It just throws an error right after build

**Comment by BennyQBD** [comment]
I've just updated the repository with tons of bug fixes, see if that fixed the issue.

**Comment by ForeverTPS** [comment]
@citruslee for Benny or any of the community to assist you need to include much more detail in the bug reports. Posting issues without all the relevant information just wastes peoples time. Without even posting an error message there is no hope of anyone helping.

**Comment by citruslee** [comment]
I check it tomorrow ASAP... @Zammalad  I wrote that the computer is not mine on which the error occured, but since then I've got back my broken pc (repaired) and recently installing visual studio and windows 8 on it, so I'll be able to tell you more, or that is it fixed...nonetheless, @BennyQBD , it's amazing what are you doing, keep it on!

**Comment by citruslee** [comment]
okay, seems to be resolved, hence it works out of the box on WIndows 8 and MSVC 2012 :)
