### ISSUE TITLE
missing some files

### ISSUE THREAD

**Issue by mamoniem** [BennyQBD/3DEngineCpp#2]
I was googling for something and found your repo. It looks interested for me, I downloaded it, but building gives errors !
I'm using vs2013 :

Error   4   error C1083: Cannot open source file: 'basicShader.cpp': No such file or directory
Error   1   error C1083: Cannot open source file: 'phongShader.cpp': No such file or directory  

just letting you know :)
In case you committed the project correctly, I might consider make the mac build/xcodeProject for you as a support. may be some one out there need it !

cheers;

**Comment by BennyQBD** [comment]
That's correct! I'm in the process of updating the repository for tutorial 60, so some of the build files aren't quite up to date. I am however keeping the Code::Blocks project up to date during the update process, so you should hopefully be able to build with that for the time being.

Thanks for bringing it up however; it's good to know I'm not living in a void where breaking the project goes completely unnoticed. I'll let you know once the build files are fully updated for tutorial 60, and hopefully there won't be any issues after that.

Cheers,
Benny

**Comment by BennyQBD** [comment]
As of now, the project and all the build files should be fully updated. Let me know if you still have trouble building.

**Comment by mamoniem** [comment]
the files are exist now, and the project works fine :+1:  I add the XCode project to my to do list for this week. and will submit to you. hopefully it helps with a way or another to spread the word.
btw, you are noticeable, otherwise Google wouldn't put you in my results ;)
