### ISSUE TITLE
Black screen issues

### ISSUE THREAD

**Issue by PlasmaDev5** [BennyQBD/3DEngineCpp#20]
Im having issues with all builds after the implementation of the profiling. From what i can tell nothing is rendered on the screen i have tried looking around and moving 
![black screen](https://cloud.githubusercontent.com/assets/3044415/3538099/887969ea-082a-11e4-96a2-9c4055cb86b4.PNG)

my computer specs are:

AMD A4-5000 APU 
8GB RAM
AMD Radeon HD 8330 & 8500M

i have tried the AMD 14.4 and 14.6 Drives

**Comment by ghost** [comment]
Try using to basic shader ?

Change renderingEngine.cpp line 43 to m_defaultShader("basicShader"),

**Comment by pythoneer** [comment]
Looks like this is related to the issue https://github.com/BennyQBD/3DEngineCpp/issues/19 seems to be it has something to do with the experimental shading stuff benny added.

**Comment by PlasmaDev5** [comment]
switching to the basic shaders fixes the issue, although rendering effects do not, i hope either the drivers get fixed or Benny puts a fix in the code

**Comment by BennyQBD** [comment]
Since this seems to be the same as #19, I'm going to close this. Any further posts about this issue should be in #19. If anyone can confirm there is a difference between this and #19, let me know and I'll reopen.
