### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by ghost** [BennyQBD/3DEngineCpp#21]
Hi, Benny. I really like your series and I am really interested to see a 3D physics engine being implemented. However, the number of classes is getting too much for one folder. Maybe splitting it up into seperate folders for rendering, profiling, etc. (Sorry, I have only known C++ for a few weeks) This is just a suggestion.

**Comment by BennyQBD** [comment]
Sorry that it's taken me so long to get around to this, but I've reorganized the project similar to how I organized the Java 3D Engine. Let me know what you think of the new organization system. If you like it, I think it's safe to close this issue.

**Comment by ghost** [comment]
It is much easier to see what pertains to what. Thank you, Benny.
