### ISSUE TITLE
Too high window sync time

### ISSUE THREAD

**Issue by zeyorama** [BennyQBD/3DEngineCpp#28]
Hey Benny,
I got a issue with my window sync time. I profile SDLSwapBuffers which calls SDL_GL_SwapWindow(window) and it needs a lot of time. On our Forward-Renderer needs it nearly the same amount of time to sync as to render, at the moment about 32ms. On my Deferred-Renderer is the render time nearly 3ms but the sync time about 60 ms. Do you have any idea whats going on?

Thanks in advance and sorry for my bad english.

**Comment by zpl-zak** [comment]
I have the same problem, is there any way to fix it? It happens on nvidia(?) mobile gpus (laptops) as far I know. I've tested it on several computers. It happens only on my laptops.

**Comment by citruslee** [comment]
try to set this in the code

_declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;

maybe you run on intel graphics, don't know if that would be a reason, but OpenGL in my own framework missed this one line and was painfully slow, but got speed eventually when I set enablement on

**Comment by zpl-zak** [comment]
Thanks, it helped me a lot.

**Comment by citruslee** [comment]
neni zac :)

**Comment by zeyorama** [comment]
This helps, thanks a lot.
Just for completion, there is an AMD equivalent:
`_declspec(dllexport) int AmdPowerXpressRequestHighPerformance  = 1;`

**Comment by citruslee** [comment]
@zeyorama oh cool, thanks, I didn't knew there is AMD counterpart of it :)

**Comment by zpl-zak** [comment]
@zeyorama thanks for the AMD equivalent!

**Comment by zeyorama** [comment]
Found it on
 http://stackoverflow.com/questions/17458803/amd-equivalent-to-nvoptimusenablement
