### ISSUE TITLE
Strange Rendering-Effect

### ISSUE THREAD

**Issue by EvilSocket1** [BennyQBD/3DEngineCpp#3]
If you just move away from the scene, some of the planes render... strange.
![Effect](https://cloud.githubusercontent.com/assets/7187058/2622188/edd954da-bc94-11e3-85da-3cf58ac1e32c.PNG)

**Comment by BennyQBD** [comment]
Try getting rid of your current copy of the repository and cloning again. Based on the screenshot, you appear to have an older version, and the new version shouldn't have this issue. If it does, I haven't been able to reproduce this effect, and would appreciate some steps on how to do so.

**Comment by EvilSocket1** [comment]
I cloned the newest version and compiled it with Visual Studio 2013 (on Windows 7). It still happens. The OpenGL Version i'm using is 3.3 (it's the newest supported by my graphic card).  It seems to be related to the distance on the Y-Axis. Changing zFar doesn't change anything, changing zNear (from 0.01 to 0.001) makes it even worse (it happens sooner). Changing zNear from 0.01 to 0.1 has the opposite effect. 
Removing the DirectionalLight has the effect, that places that were bright are just transparent.

Update: I tried different Computers and it happens on some of them, but not on all of them.

**Comment by SomeSoftwareGuy** [comment]
This is probably ZFighting. It appears, if your Z Buffer (which should be 16 (see Window.cpp)) is too small to distinguish between the big and the small planes. Here's a calculator for that: http://www.sjbaker.org/steve/omniv/love_your_z_buffer.html

You must make zNear bigger or make your Z Buffer bigger.

**Comment by BennyQBD** [comment]
I've looked into the issue and here's what I've found:

Beyond a certain depth value, the ambient pass seems to stop writing values to the depth buffer. You can observe this by commenting out the lighting code from the rendering engine and setting the camera's zFar to 100.

I tried changing the depth precision from 16 bits to 24, and found no change in behavior, suggesting that it's not a precision issue.

Unless I've missed something in the code, this seems to be a driver bug. The fact that it only happens on some computers but not others further supports this.

My suggestion is to set the Camera's zNear to 0.1 and zFar to 1000.0; these values seem to minimize but not eliminate the effect. If you include an effect like render fog for distant objects, this issue should become effectively unnoticeable.

If someone can find anything that suggests it's an issue in the code and not the drivers, I'll be happy to investigate further. Until then, this workaround seems to be the best "solution" that I've found.

**Comment by ForeverTPS** [comment]
Just to add more confusion, when I changed the depth precision from 16 to 24 it DID fix the issue for me so running with 24bit it works without issue on Windows 7 x64 (GeForce 770) and on OSX Mavericks on a latest gen MBP. 16bit works fine on Windows but not OSX.

**Comment by BennyQBD** [comment]
Solved it.

As usual, the code was doing precisely what I told it to. If part of an object lies past the zFar, it gets clipped, and that part won't be written to the depth buffer; so the depth buffer stays at whatever the clear value is. 

However, when lighting, it checks if depth values are equal. It'll render the object, the part that's past ZFar will get clipped again, and it will end up with the same default depth buffer value. Thus, anything past the far clip plane ultimately ends up being light and additively blended into the image, even if the rest of the object was clipped. In other words, it produces the effect shown in the issue.

Proposed solution: When skyboxes are implemented, offset the skybox in by a slight amount. That way, the object's depth will be compared with the skybox's depth, and they won't be equal. Thus, all objects past the far clip plane end up being clipped, as they should be.

Any other input or proposed solutions would be appreciated!

**Comment by BennyQBD** [comment]
Even better, I appear to have found a solution by manipulating GL_DEPTH_CLAMP.

Try now, and see if you can produce the issue.

**Comment by BennyQBD** [comment]
I've heard no reports of this issue since this post. Since the original author seems to be unable to confirm, I'm going to assume this issue is resolved. If anyone else can confirm that, I'd appreciate it. If anyone can still produce this problem, please post and I'll reopen this issue.

Until then however, I'm going to say this issue is closed.
