### ISSUE TITLE
Normalmapping shadowing in the wrong direction 

### ISSUE THREAD

**Issue by pythoneer** [BennyQBD/3DEngineCpp#5]
I know you talked about that in your Video[*] and maybe you alredy fixed this but i just want to catch your attention in case  you overlooked this.
![3dnormal](https://cloud.githubusercontent.com/assets/1102097/2812116/47e2aabc-ce42-11e3-8877-4440d03e8bf6.png)

as one can cleary see, the light is coming from the yellow direction. the shadowed part (green) should be lit by the light and the highlights (red) should be exactly on the other side of the brick. 

[*] http://youtu.be/dF5rOveGOJc?t=24m20s

**Comment by zeyorama** [comment]
Benny talked about this issue. Flip your normal map at the y axis and everything looks like intended.

**Comment by BennyQBD** [comment]
Zeyorama is correct. I've left this in as an example of the discrepancy between the two styles of normal maps. I don't think it's a big deal as long as people are aware that it's intentional, but if you think I should fix it anyways, let me know and I'll be glad to do so.

**Comment by pythoneer** [comment]
I am totally aware of the fact that you mentioned this in the video. And i am able ( and already did ) to resolve this. Do not fix this, if this was your intention – but it is somehow problematic that it is not mentioned to the user ( except the video ). This is somehow confusing – as it was to me. I know that you mentioned this in your Video ... but i could not recall the hole video and what you talked about that in detail. 

@BennyQBD: for this cases – maybe – you could tag your projects or use branches. But this as a hole could lead to confusion; in my opinion

best Regards

**Comment by drekryan** [comment]
I think a comment in the source code would be enough explanation. Just right the code to reverse it and leave it commented and they can uncomment it if they have the issue. We can't hold your hand all the way there. I think that's clear enough.

**Comment by pythoneer** [comment]
I have no problem with this in either way. Just wanna point this out – and maybe the "examples" should be correct and leave a comment for the peoples who use there own assets. Or, and maybe this could be intentional, leave the example wrong so everyone have to look at the code and maybe find the comment where it is mentioned "to change it depending on the way your assets are created" ... this was just for the purpose of a discussion.

**Comment by BennyQBD** [comment]
How about this: Where the incorrect normal map is loaded, I'll put in a comment describing that it's incorrect, that it's intentional, and how it can be fixed. That way there's no confusion. Sound fair?

**Comment by pythoneer** [comment]
I fully support your suggestion and i think we have elaborated this topic sufficiently to close it :)
